### ISSUE TITLE
Installation problem for people in China 

### ISSUE THREAD

**Issue by mhadnanali** [GraphCL/PyGCL#17]
Installation Issue, While I already have installed dgl manually. but it looks like you have a requirements file that imposing to install the wrong version or something. 
note: I am trying to install via pip mirror because I am in China. I tried both USTC and Tshinghua mirror and both ends up with the same error. 

DGL latest version is 0.6.1 as per the below screenshot, while Pygcl requires 0.7 ? 
I already installed the latest version as shown in error. 
pip install  -i https://mirrors.aliyun.com/pypi/simple/ dgl==0.7a210527

What I am doing wrong here?

![image](https://user-images.githubusercontent.com/15828557/134755613-beaa4dd9-46b0-4c63-b742-9959d3882689.png)

![image](https://user-images.githubusercontent.com/15828557/134753926-4c22effa-7b73-4bdc-86ef-eaf680077475.png)

**Comment by SXKDZ** [comment]
Hi Ali,
Please follow [this page](https://www.dgl.ai/pages/start.html) for installing dgl since its package is provided by an external link.

**Comment by mhadnanali** [comment]
It makes no difference. Maybe if you change the requirement to dgl 0.6 it may solve the problem. as 0.6 is stable version. 
![image](https://user-images.githubusercontent.com/15828557/134756985-a12b28a1-76fb-49b8-960e-8aa3a30a2397.png)

**Comment by SXKDZ** [comment]
It seems that you have already installed dgl 0.6. Therefore you need to uninstall the older version at first and try again to install the new ones.

**Comment by mhadnanali** [comment]
Also, please update your documentation of PyGCL, but I don't understand how I am going to use it after installation. I am also reading the literature of GCL and am interested to work in this field. i hope I can use PyGCL for implementation. but for now, I don't understand. That is what to do next after installation. or how to run the examples. I hope I am not disturbing you.

**Comment by SXKDZ** [comment]
Thanks for your advice. After you installed PyGCL, you can refer to [this paper](https://arxiv.org/abs/2109.01116) for the four contrastive components that we are concerned in this package. We have also provided a brief introduction in the README file to give a big picture of the package. We are very sorry that the doc is not ready since our dev team (consisting of only two people) is chasing some stringent deadlines for now. We endeavor to make our library more easy to use but please give us some time.

**Comment by mhadnanali** [comment]
I am already this paper and I already have read your other paper "GRACE", hope to see more from you. best of luck.

**Comment by HangerYang** [comment]
I followed the instruction and download it from the external link, but it seemed the prompt still suggested that the version for DGL I had was older than 0.7. I wonder what the problem could be.

**Comment by SXKDZ** [comment]
> I followed the instruction and download it from the external link, but it seemed the prompt still suggested that the version for DGL I had was older than 0.7. I wonder what the problem could be.

You may try `conda list | grep dgl` and check whether the installed version is newer than 0.7. For a temporary solution, you can also remove this specific version requirement by checking out the repo, modifying `setup.cfg`, and installing locally `pip install .`. Currently we are refactoring the augmentation class which relies on many builtin functions provided by dgl. It is thus suggested to follow the requirement. We will review the least possible requirement of dgl in the next release. Please stay tuned and thanks for your interest on our library!

**Comment by mhadnanali** [comment]
@HangerYang 
I just installed it 2 days ago again. its working file. 
install dgl with "pip install dgl -f https://data.dgl.ai/wheels/repo.html"

**Comment by HangerYang** [comment]
> > I followed the instruction and download it from the external link, but it seemed the prompt still suggested that the version for DGL I had was older than 0.7. I wonder what the problem could be.
> 
> You may try `conda list | grep dgl` and check whether the installed version is newer than 0.7. For a temporary solution, you can also remove this specific version requirement by checking out the repo, modifying `setup.cfg`, and installing locally `pip install .`. Currently we are refactoring the augmentation class which relies on many builtin functions provided by dgl. It is thus suggested to follow the requirement. We will review the least possible requirement of dgl in the next release. Please stay tuned and thanks for your interest on our library!

I used the cloning repo method and it worked. Thank you.

**Comment by HangerYang** [comment]
> @HangerYang I just installed it 2 days ago again. its working file. install dgl with "pip install dgl -f https://data.dgl.ai/wheels/repo.html"

Thank you for your reply :)

**Comment by HoytWen** [comment]
> > @HangerYang I just installed it 2 days ago again. its working file. install dgl with "pip install dgl -f https://data.dgl.ai/wheels/repo.html"
> 
> Thank you for your reply :)

Hi, I have dgl-cu111 0.7.1 installed in my device, but when I try to install PyGCL, it returns an error that says the dgl I installed does not meet the requirement. I wonder is this because PyGCL can only work with the non-cuda version of dgl?

**Comment by SXKDZ** [comment]
Hello HoytWen, we will remove the specific version requirement in the setup configuration, as the newest dgl no longer hosts in PyPi, so that when `pip install PyGCL`, there won't be a matched version for `dgl`.

**Comment by SXKDZ** [comment]
> > > @HangerYang I just installed it 2 days ago again. its working file. install dgl with "pip install dgl -f https://data.dgl.ai/wheels/repo.html"
> > 
> > 
> > Thank you for your reply :)
> 
> Hi, I have dgl-cu111 0.7.1 installed in my device, but when I try to install PyGCL, it returns an error that says the dgl I installed does not meet the requirement. I wonder is this because PyGCL can only work with the non-cuda version of dgl?

I have just checked with the dgl team. Currently they maintain two packages of dgl, `dgl` for CPU support and `dgl-cu***` for CUDA support. Therefore, when installing PyGCL via pip, pip will only check the dependency for `dgl`. We will provide a note regarding this problem in the readme.

**Comment by HoytWen** [comment]
Thanks a lot!
