### ISSUE TITLE
Can't find trial.py 

### ISSUE THREAD

**Issue by Niuchx** [GraphCL/PyGCL#26]
Thanks for opensourcing.

When I read "A.2. Instructions for Reproducing Results in Our Work" section in the paper, this section describles how to reproduce the experiments by running _trial.py_. But I can't find _trial.py_ file in this repository. 

It would be appreciated if anyone could help tell me where to find the file.

**Comment by SXKDZ** [comment]
Thanks for your remind. Regarding the reproducibility of our benchmark paper, we will open a new repository for all codes. Currently you can download the script in the [supplementary material](https://openreview.net/forum?id=UuUbIYnHKO) section.
