### ISSUE TITLE
How to run GraphCL with Node classification tasks? 

### ISSUE THREAD

**Issue by noelsjw63** [GraphCL/PyGCL#27]
Dear authors, this is a great job in Graph Contrastive learning field. But I am encountering 2 small problems.  
1. When I run GRACE with large datasets such as WikiCS, then the CUDA out of memory problem occurs. 
2. How to run GraphCL on node classification problem? 
I am much thankful if you can reply to me !

**Comment by SXKDZ** [comment]
Hi! Thanks for your interest on our work. For large-scale datasets, you can slightly lower the hidden dimension or try negative-sample-free models such as BGRL and GBT. [These two models plus our GRACE](https://github.com/GraphCL/PyGCL/blob/main/examples) all target at node classification and can be found in the `examples` folder.
