### ISSUE TITLE
About the ''edge_weight'' in ''PPRDiffusion'' augment

### ISSUE THREAD

**Issue by wwb19951230** [GraphCL/PyGCL#29]
Thanks for opensourcing.

When I read examples "MVGRL_graph.py", I found  only augmented 'edge_index2' and 'x2' were used as the input of 'gcn2'. Why did not input the  augmented  ''edge_weight2'' to 'gcn2' ? 

It would be appreciated if anyone could help tell me the reason.

**Comment by SXKDZ** [comment]
Thanks for mentioning this problem. We will take a closer look.

**Comment by SXKDZ** [comment]
Fixed. Please checkout the newest develop branch. Thanks for your kind suggestion!
