### ISSUE TITLE
Label leakage

### ISSUE THREAD

**Issue by SXKDZ** [GraphCL/PyGCL#33]
https://github.com/GraphCL/PyGCL/blob/33c7d1c53c6e0f5458122ecad59cd69f9e1d4af6/GCL/model/sampler.py#L120

**Comment by Linyxus** [comment]
https://github.com/GraphCL/PyGCL/blob/33c7d1c53c6e0f5458122ecad59cd69f9e1d4af6/GCL/model/sampler.py#L124

https://github.com/GraphCL/PyGCL/blob/33c7d1c53c6e0f5458122ecad59cd69f9e1d4af6/GCL/model/sampler.py#L132

It seems that extra positive/negative will only be added for nodes in the training set.
