### ISSUE TITLE
Could not find dgl>=0.7 when installing PyGCL

### ISSUE THREAD

**Issue by scottshufe** [GraphCL/PyGCL#34]
Hello pygcl team, thanks for your excellent work!

It seems that the latest version of DGL is 0.6.1 when I install it following the official instruction. Then I meet the error "Could not find dgl>=0.7" when I try to install PyGCL. Could you please give me some suggestions to fix this issue?

**Comment by SXKDZ** [comment]
Hi! Thanks for reaching out. I suggest you could install the newest version by following [its official homepage](https://www.dgl.ai/pages/start.html), as the 0.7 version is not available in pypi.

**Comment by scottshufe** [comment]
OK. I'll try it. Thanks for your reply!
