### ISSUE TITLE
About the installation

### ISSUE THREAD

**Issue by CocoGzh** [GraphCL/PyGCL#35]
I have installed dgl-cu11 0.7.2. When I installed pygcl, I was prompted with "error: no matching distribution found for DGL > = 0.7 (from pygcl)". Do I have to install DGL without CUDA?

**Comment by Linyxus** [comment]
Could you paste the result of `pip list | grep dgl` in your environment?

**Comment by CocoGzh** [comment]
I don't know what you mean. Is this?
Package                            Version
---------------------------------- -----------------
absl-py                            0.15.0
aiohttp                            3.7.4.post0
alabaster                          0.7.12
aliyun-python-sdk-core             2.13.35
aliyun-python-sdk-kms              2.15.0
anaconda-client                    1.7.2
anaconda-navigator                 1.10.0
anaconda-project                   0.8.3
anndata                            0.7.6
annoy                              1.17.0
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0.2
async-generator                    1.10
async-timeout                      3.0.1
atomicwrites                       1.4.0
attrs                              20.3.0
autopep8                           1.5.4
Babel                              2.8.1
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
backports.zoneinfo                 0.2.1
bbknn                              1.5.1
bcrypt                             3.2.0
beautifulsoup4                     4.9.3
bitarray                           1.6.1
bkcharts                           0.2
bleach                             3.2.1
bokeh                              2.2.3
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
cachetools                         4.2.4
captum                             0.4.1
certifi                            2021.5.30
cffi                               1.14.3
chardet                            3.0.4
charset-normalizer                 2.0.6
click                              8.0.1
cloudpickle                        1.6.0
clyent                             1.2.2
colorama                           0.4.4
commonmark                         0.9.1
comtypes                           1.1.7
conda                              4.10.3
conda-build                        3.20.5
conda-package-handling             1.7.2
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
crcmod                             1.7
cryptography                       3.1.1
cycler                             0.10.0
Cython                             0.29.21
cytoolz                            0.11.0
dask                               2.30.0
decorator                          4.4.2
defusedxml                         0.6.0
dgl-cu111                          0.7.2
diff-match-patch                   20200713
distributed                        2.30.1
docrep                             0.3.2
docutils                           0.16
dunamai                            1.6.0
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
fbpca                              1.0
filelock                           3.3.0
flake8                             3.8.4
Flask                              1.1.2
fsspec                             2021.10.1
future                             0.18.2
geosketch                          1.2
get-version                        3.5
gevent                             20.9.0
glob2                              0.7
google-auth                        2.3.0
google-auth-oauthlib               0.4.6
googledrivedownloader              0.4
greenlet                           0.4.17
grpcio                             1.41.0
h5py                               2.10.0
harmonypy                          0.0.5
HeapDict                           1.0.1
html5lib                           1.1
huggingface-hub                    0.0.18
idna                               3.2
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 2.0.0
iniconfig                          1.1.1
intervaltree                       2.1.0
ipdb                               0.13.9
ipykernel                          5.3.4
ipython                            7.19.0
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isodate                            0.6.0
isort                              5.6.4
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.1
Jinja2                             2.11.2
jmespath                           0.10.0
joblib                             1.0.1
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.7
jupyter-console                    6.2.0
jupyter-contrib-core               0.3.3
jupyter-contrib-nbextensions       0.5.1
jupyter-core                       4.6.3
jupyter-highlight-selected-word    0.2.0
jupyter-latex-envs                 1.4.6
jupyter-nbextensions-configurator  0.4.1
jupyterlab                         2.2.6
jupyterlab-pygments                0.1.2
jupyterlab-server                  1.2.0
keyring                            21.4.0
kiwisolver                         1.3.0
lazy-object-proxy                  1.4.3
legacy-api-wrap                    1.2
leidenalg                          0.8.7
libarchive-c                       2.9
littleutils                        0.2.2
llvmlite                           0.34.0
locket                             0.2.0
loompy                             3.0.6
louvain                            0.7.0
lxml                               4.6.1
Markdown                           3.3.4
MarkupSafe                         1.1.1
matplotlib                         3.3.2
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.2.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.2
more-itertools                     8.6.0
mpmath                             1.1.0
msgpack                            1.0.0
multidict                          5.2.0
multipledispatch                   0.6.0
NaiveDE                            1.2.0
natsort                            7.1.1
navigator-updater                  0.2.1
nbclient                           0.5.1
nbconvert                          6.0.7
nbformat                           5.0.8
nest-asyncio                       1.4.2
networkx                           2.5
nose                               1.3.7
notebook                           6.1.4
numba                              0.51.2
numexpr                            2.7.1
numpy                              1.21.2
numpy-groupies                     0.9.14
numpydoc                           1.1.0
oauthlib                           3.1.1
ogb                                1.3.2
olefile                            0.46
openpyxl                           3.0.5
opt-einsum                         3.3.0
oss2                               2.15.0
outdated                           0.2.1
packaging                          21.0
pandas                             1.4.1
pandocfilters                      1.4.3
paramiko                           2.7.2
parso                              0.7.0
partd                              1.1.0
path                               15.0.0
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             8.0.1
pip                                20.2.4
pkginfo                            1.6.1
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.8.0
prompt-toolkit                     3.0.8
protobuf                           3.19.0
psutil                             5.7.2
py                                 1.9.0
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycryptodome                       3.12.0
pycurl                             7.43.0.6
pyDeprecate                        0.3.0
pydocstyle                         5.1.1
pyflakes                           2.2.0
Pygments                           2.7.2
pylint                             2.6.0
PyNaCl                             1.4.0
pynndescent                        0.5.4
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
pyreadline                         2.1
pyreadr                            0.4.4
pyro-api                           0.1.2
pyro-ppl                           1.7.0
pyrsistent                         0.17.3
PySocks                            1.7.1
pytest                             0.0.0
python-dateutil                    2.8.1
python-igraph                      0.9.6
python-jsonrpc-server              0.4.0
python-language-server             0.35.1
pytorch-lightning                  1.3.8
pytz                               2020.1
pytz-deprecation-shim              0.1.0.post0
PyWavelets                         1.1.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             5.4.1
pyzmq                              19.0.2
QDarkStyle                         2.8.1
QtAwesome                          1.0.1
qtconsole                          4.7.7
QtPy                               1.9.0
rdflib                             6.0.1
regex                              2021.9.30
requests                           2.26.0
requests-oauthlib                  1.3.0
rich                               10.11.0
rope                               0.18.0
rpy2                               3.4.5
rsa                                4.7.2
Rtree                              0.9.4
ruamel-yaml                        0.15.87
ruamel.yaml                        0.17.16
ruamel.yaml.clib                   0.2.6
sacremoses                         0.0.46
scanorama                          1.7.1
scanpy                             1.8.0
scETM                              0.5.0
scikit-image                       0.17.2
scikit-learn                       0.23.2
scipy                              1.5.2
scvelo                             0.2.4
scvi-tools                         0.14.3
seaborn                            0.11.0
Send2Trash                         1.5.0
setuptools                         58.1.0
setuptools-scm                     6.3.2
simplegeneric                      0.8.1
sinfo                              0.3.4
singledispatch                     3.4.0.3
sip                                4.19.13
six                                1.16.0
sklearn                            0.0
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.2.2
soupsieve                          2.0.1
SpatialDE                          1.1.3
Sphinx                             3.2.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.1.5
spyder-kernels                     1.9.4
SQLAlchemy                         1.3.20
statsmodels                        0.12.0
stdlib-list                        0.8.0
sympy                              1.6.2
tables                             3.6.1
tabulate                           0.8.9
tblib                              1.7.0
tensorboard                        2.7.0
tensorboard-data-server            0.6.1
tensorboard-plugin-wit             1.8.0
tensorboardX                       2.4.1
terminado                          0.9.1
testpath                           0.4.4
texttable                          1.6.4
threadpoolctl                      2.1.0
tifffile                           2020.10.1
timm                               0.4.12
tokenizers                         0.10.3
toml                               0.10.2
tomli                              1.2.1
toolz                              0.11.1
torch                              1.10.2+cu113
torch-cluster                      1.5.9
torch-geometric                    2.0.2
torch-scatter                      2.0.8
torch-sparse                       0.6.12
torch-spline-conv                  1.2.1
torchaudio                         0.10.2+cu113
torchmetrics                       0.6.0
torchvision                        0.11.3+cu113
tornado                            6.0.4
tqdm                               4.62.3
traitlets                          5.0.5
transformers                       4.11.2
typing-extensions                  3.10.0.2
tzdata                             2021.5
tzlocal                            4.1
ujson                              4.0.1
umap-learn                         0.4.6
unicodecsv                         0.14.1
urllib3                            1.26.7
watchdog                           0.10.3
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.35.1
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.11.2
xlrd                               1.2.0
XlsxWriter                         1.3.7
xlwings                            0.20.8
xlwt                               1.3.0
xmltodict                          0.12.0
yacs                               0.1.8
yapf                               0.30.0
yarl                               1.7.0
zepid                              0.9.0
zict                               2.0.0
zipp                               3.4.0
zope.event                         4.5.0
zope.interface                     5.1.2

**Comment by CocoGzh** [comment]
> Could you paste the result of `pip list | grep dgl` in your environment?

Do you need it? Thanks!

**Comment by Linyxus** [comment]
Please install `dgl` with `conda`.

**Comment by CocoGzh** [comment]
> Please install `dgl` with `conda`.

Whether I use pip DGL or conda DGL, it reminds me that I need the version of DGL > = 0.7. I tried dgl-cu111 0.7.2 and dgl-cu111 0.8.0 post1。

After I delete DGL > = 0.7 in "setup.cfg" and install it. It works but an error occurs when importing GCL, specifically from torch_ Spark import sparsetensor, coalesce, I'd like to know your torch_sparse version.

thank you!

**Comment by CocoGzh** [comment]
> Please install `dgl` with `conda`.

Specifically,

Traceback (most recent call last):
  File "J:/project/script.py", line 14, in <module>
    import GCL
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\10360\anaconda3\lib\site-packages\pygcl-0.1.1-py3.8.egg\GCL\__init__.py", line 2, in <module>
    # @author: Xingyan Liu
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\10360\anaconda3\lib\site-packages\pygcl-0.1.1-py3.8.egg\GCL\augmentors\__init__.py", line 3, in <module>
    
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\10360\anaconda3\lib\site-packages\pygcl-0.1.1-py3.8.egg\GCL\augmentors\rw_sampling.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\10360\anaconda3\lib\site-packages\pygcl-0.1.1-py3.8.egg\GCL\augmentors\functional.py", line 7, in <module>
  File "C:\Users\10360\anaconda3\lib\site-packages\torch_sparse\__init__.py", line 14, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "C:\Users\10360\anaconda3\lib\site-packages\torch\_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "C:\Users\10360\anaconda3\lib\ctypes\__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] 找不到指定的程序。

Process finished with exit code 1

**Comment by CocoGzh** [comment]
> Please install `dgl` with `conda`.

All questions have been resolved.  
I update pytorch, which results a wrong vision of torch_gemotric. 
Thx!

**Comment by SXKDZ** [comment]
Glad to see it has been resolved! Feel free to reach out if any other problems occur.
