### ISSUE TITLE
EdgeRemoving

### ISSUE THREAD

**Issue by GlancerZ** [GraphCL/PyGCL#41]
Awesome work! But I am confused about A.EdgeRemoving(pe=0.3), which means keep 0.3 or drop 0.3?

**Comment by Linyxus** [comment]
Thank you for your interest in our toolkit. The `pe` is the probability of dropping edges. We are documenting our library to explain the usage and the meaning of arguments. :D

**Comment by Linyxus** [comment]
So I guess we can close this issue now.
