### ISSUE TITLE
A problem about PyGCL model implement project.

### ISSUE THREAD

**Issue by un0o7** [GraphCL/PyGCL#42]
You defined the project while not being used.
![image](https://user-images.githubusercontent.com/57668141/160228908-adcb19f6-5ee1-4e5a-8053-5d66ef1a37dd.png)

**Comment by Linyxus** [comment]
We used the projection here: https://github.com/GraphCL/PyGCL/blob/c2f4dc73e449d26a109dbefede287ea0fca93c4b/examples/GraphCL.py#L81.

**Comment by un0o7** [comment]
Thanks
